---
language: rust
rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly

cache:
  - cargo

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

script:
  - mdbook build movie-night-book && mdbook test movie-night-book

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: movie-night-book/book
  keep-history: false
  repo: oknozor/oknozor.github.io
  branches:
    only:
      - master
  fast_finish: true
