language: rust
rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: movie-night-book
  keep-history: false
  on:
    branch: master